# Generated by Django 5.1.4 on 2025-04-11 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_all_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL, verbose_name='provider'),
            preserve_default=False,
        ),
    ]
